name: Testing and Docker Image Build/Push CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up Python 3.9
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.9
      - 
        name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # TODO: add actual tests where applicable
  docker:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.10.6
          buildkitd-flags: --debug
      - 
        id: authgcp
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_RESOURCE_NAME }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          access_token_lifetime: 600s
      - 
        name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GAR_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.authgcp.outputs.access_token }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.GAR_REPO }}/${{ vars.APP_NAME }}:${{steps.get-tags.outputs.tags }}
